### ISSUE TITLE
Reversing the array operations

### ISSUE THREAD

**Issue by ayu-st12** [RyanFehr/HackerRank#32]
https://github.com/RyanFehr/HackerRank/blob/master/Algorithms/Implementation/Electronics%20Shop/Solution.java

Ryan...above mentioned "Solution.java" works fine, when keyboards arrays is in descending order and drives in ascending. But i cant figure out whats the issue when i reverse it.. Like putting drives in descending order and keyboards in ascending order. I'm getting a wrong output!

import java.io.*;
import java.util.*;
import java.text.*;
import java.math.*;
import java.util.regex.*;

public class Solution {

    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        int s = in.nextInt();
        int n = in.nextInt();
        int m = in.nextInt();
        Integer[] keyboards = new Integer[n];
        for(int keyboards_i=0; keyboards_i < n; keyboards_i++){
            keyboards[keyboards_i] = in.nextInt();
        }
        Integer[] drives = new Integer[m];
        for(int drives_i=0; drives_i < m; drives_i++){
            drives[drives_i] = in.nextInt();
        }

        Arrays.sort(drives, Collections.reverseOrder());//Descending order
        Arrays.sort(keyboards);
        int max = -1;
       
        for(int i=0;i<n;i++){
            for(int j=0;j<m;j++){
                if(keyboards[i] + drives[j] > s){break;}
                if(keyboards[i] + drives[j] > max){
                    max = keyboards[i] + drives[j];
                }
            }
        }
        
        //int moneySpent = getMoneySpent(keyboards, drives, s);
        System.out.println(max);
    }
}

[input.txt](https://github.com/RyanFehr/HackerRank/files/1033325/input.txt)
[output.txt](https://github.com/RyanFehr/HackerRank/files/1033326/output.txt)

**Comment by RyanFehr** [comment]
The reason you are receiving incorrect output has to do with how the for loop works, We use our for loop to advance to the next drive until we fail/hit our break case. Our break case is when we have matched a expensive keyboard with a drive, and we know that all future drives will also break that case, because they are ordered ascending. Now if we switch to where the drives are descending, when we hit that break case, we can no longer make the same assumption. Thus by sorting them differently you will miss out on a few combinations of keyboard/drive and when one of those is the most optimal, the code above will instead return a sub-optimal solution. Hope this helps to explain.

**Comment by ayu-st12** [comment]
yeah....got it! Thank you so much Ryan :+1:
